# Generated by Django 6.0.2 on 2026-02-12 18:48

import scheduling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletheme',
            name='created_at',
            field=models.DateTimeField(default=scheduling.models._now),
        ),
        migrations.AlterField(
            model_name='scheduletheme',
            name='updated_at',
            field=models.DateTimeField(default=scheduling.models._now),
        ),
        migrations.AlterField(
            model_name='scheduleweek',
            name='created_at',
            field=models.DateTimeField(default=scheduling.models._now),
        ),
        migrations.AlterField(
            model_name='scheduleweek',
            name='updated_at',
            field=models.DateTimeField(default=scheduling.models._now),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(default=scheduling.models._now),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(default=scheduling.models._now),
        ),
    ]
